### PR TITLE
Ark dependency in metadata.rb

### PR DESCRIPTION
**Pull request by gsaslis**

### CODE REVIEW

**Comment by gsaslis** [comment]
@arussel so, i've ended up having to add a lot of new stuff to the cookbook ... would you like me to open separate PRs for this? 

would you have some time to review and merge them in ? (btw, I would also happily join the maintainers of your repo to help with merging more PRs ... noticed @twish has also started a fork .. )

**Comment by arussel** [comment]
@gsaslis thannks for the request, I think I gave you access, can you check that it works.

**Comment by gsaslis** [comment]
Thanks @arussel!  yeah - that worked!  : ) 
Will work on adding the features soon

**Comment by gsaslis** [comment]
closing this in favour of new PR based on branch, that's specific to the issue, for clarity

**Pull request closed without merging**
